### ISSUE TITLE
TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by nthieu173** [robotarium/vizier#5]
When I try to create a new Vizier Node:
```
node = vizier.node.Node("localhost",1884, node_descriptor)
node.start()
```
If fails:
```
Traceback (most recent call last):
  File "vizer_test.py", line 8, in <module>
    node = vizier.node.Node("localhost",1884, node_descriptor)
  File "/home/hieu/.local/lib/python3.6/site-packages/vizier/node.py", line 86, in __init__
    self._expanded_links, self._requested_links = utils.generate_links_from_descriptor(self._node_descriptor)
  File "/home/hieu/.local/lib/python3.6/site-packages/vizier/utils.py", line 242, in generate_links_from_descriptor
    x['required'] = False
TypeError: 'str' object does not support item assignment
```
This is my node_descriptor file:
```
{
  "end_point" : "controller",
  "links" :
  {
    "/input" :
    {
      "links" : {},
      "type": "STREAM"
    }
  },
  "requests" : ["robot/state"]
}
```
It seems that this is a recent error since when I was using this for our SwimmingSwarm project a few weeks ago, there wasn't any error.
Can you tell me if I was doing anything wrong and, if I wasn't, how far back should I revert the commits to avoid this error?

**Comment by pglotfel** [comment]
I've been making some breaking changes lately and honestly didn't realize other people were using this.  My bad!

You should be able to fix your error by making the following adjustment to your node descriptor
```
{
  "end_point" : "controller",
  "links" :
  {
    "/input" :
    {
      "links" : {},
      "type": "STREAM"
    }
  },
  "requests" : [{"link": "robot/state", "type": <type_of_robot/state>, "required": true/false}]
}
```

If you want a concrete example, check out the updated examples.

**Comment by nthieu173** [comment]
Thank you! After updating the node descriptor, it works now!
